FROM golang:1.24.0-alpine AS builder

WORKDIR /app

# Copy the entire parakeet project
COPY . .

# Move to the backend directory
WORKDIR /app/examples/83-web-chat-bot-ollama/backend

# Update go.mod to point to the root of the copied parakeet code
RUN go mod edit -replace github.com/parakeet-nest/parakeet=/app

# Build the application
RUN go mod download
RUN go build -o web-chat-bot

FROM scratch
WORKDIR /app
COPY --from=builder /app/examples/82-web-chat-bot-model-runner/backend/web-chat-bot .

CMD ["./web-chat-bot"]