FROM golang:1.24.0-alpine AS builder

WORKDIR /app
RUN apk add --no-cache git

# Copy the entire parakeet project
COPY . .

# Move to the backend directory
WORKDIR /app/examples/72-gitingest-es/create-embeddings

# Update go.mod to point to the root of the copied parakeet code
RUN go mod edit -replace github.com/parakeet-nest/parakeet=/app

# Build the application
RUN go mod download
RUN go build -o create-embeddings

FROM scratch
WORKDIR /app
COPY --from=builder /app/examples/72-gitingest-es/create-embeddings .

CMD ["./create-embeddings"]